In [3]:
import pandas as pd

df_initial = pd.read_csv("https://cocl.us/sanfran_crime_dataset")
df_initial

,IncidntNum,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,Address,X,Y,Location,PdId
0,120058272,WEAPON LAWS,POSS OF PROHIBITED WEAPON,Friday,01/29/2016 12:00:00 AM,11:00,SOUTHERN,"ARREST, BOOKED",800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.403404791479)",12005827212120
1,120058272,WEAPON LAWS,"FIREARM, LOADED, IN VEHICLE, POSSESSION OR USE",Friday,01/29/2016 12:00:00 AM,11:00,SOUTHERN,"ARREST, BOOKED",800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.403404791479)",12005827212168
2,141059263,WARRANTS,WARRANT ARREST,Monday,04/25/2016 12:00:00 AM,14:59,BAYVIEW,"ARREST, BOOKED",KEITH ST / SHAFTER AV,-122.388856,37.729981,"(37.7299809672996, -122.388856204292)",14105926363010
3,160013662,NON-CRIMINAL,LOST PROPERTY,Tuesday,01/05/2016 12:00:00 AM,23:50,TENDERLOIN,NONE,JONES ST / OFARRELL ST,-122.412971,37.785788,"(37.7857883766888, -122.412970537591)",16001366271000
4,160002740,NON-CRIMINAL,LOST PROPERTY,Friday,01/01/2016 12:00:00 AM,00:30,MISSION,NONE,16TH ST / MISSION ST,-122.419672,37.765050,"(37.7650501214668, -122.419671780296)",16000274071000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
150495,161061000,ASSAULT,BATTERY,Friday,12/30/2016 12:00:00 AM,21:01,PARK,NONE,OAK ST / STANYAN ST,-122.453982,37.771428,"(37.7714278595913, -122.453981622365)",16106100004134
150496,176000742,NON-CRIMINAL,LOST PROPERTY,Friday,12/30/2016 12:00:00 AM,08:00,CENTRAL,NONE,JACKSON ST / SANSOME ST,-122.401857,37.796626,"(37.7966261239618, -122.401857374739)",17600074271000
150497,176000758,LARCENY/THEFT,PETTY THEFT OF PROPERTY,Thursday,12/29/2016 12:00:00 AM,20:00,CENTRAL,NONE,PINE ST / TAYLOR ST,-122.412269,37.790673,"(37.7906727649886, -122.41226909106)",17600075806372
150498,176000764,LARCENY/THEFT,GRAND THEFT OF PROPERTY,Friday,12/30/2016 12:00:00 AM,10:00,CENTRAL,NONE,200 Block of STOCKTON ST,-122.406659,37.788275,"(37.7882745285785, -122.406658711008)",17600076406374
150499,179002868,OTHER OFFENSES,"FRAUDULENT GAME OR TRICK, OBTAINING MONEY OR P...",Friday,12/02/2016 12:00:00 AM,14:00,SOUTHERN,NONE,800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.403404791479)",17900286809024

In [4]:
df_PdDistrict = df_initial[['PdDistrict', 'X']]


df_sfcrime = df_PdDistrict.groupby(['PdDistrict']).count()

df_sfcrime = df_sfcrime.reset_index()
df_sfcrime.columns = ['Neighborhood', 'Count']
df_sfcrime.head(10)

  Neighborhood  Count
0      BAYVIEW  14303
1      CENTRAL  17666
2    INGLESIDE  11594
3      MISSION  19503
4     NORTHERN  20100
5         PARK   8699
6     RICHMOND   8922
7     SOUTHERN  28445
8      TARAVAL  11325
9   TENDERLOIN   9942

In [8]:

#Choropleth map

!conda install -c conda-forge folium=0.5.0 --yes
!pip install folium
import folium

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

Requirement already satisfied: folium in c:\users\vb\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: branca in c:\users\vb\anaconda3\lib\site-packages (from folium) (0.4.1)
Requirement already satisfied: jinja2 in c:\users\vb\anaconda3\lib\site-packages (from folium) (2.11.1)
Requirement already satisfied: requests in c:\users\vb\anaconda3\lib\site-packages (from folium) (2.22.0)
Requirement already satisfied: six in c:\users\vb\anaconda3\lib\site-packages (from folium) (1.14.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\vb\anaconda3\lib\site-packages (from jinja2->folium) (1.1.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\vb\anaconda3\lib\site-packages (from requests->folium) (2019.11.28)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\vb\anaconda3\lib\site-packages (from requests->folium) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\vb\anaconda3\lib\site-packages (from requests->folium) (1.25.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\vb\anaconda3\lib\site-packages (from requests->folium) (3.0.4)

In [17]:
sanfran_geo = r'world_countries.json'

In [18]:
sanfran_map = folium.Map(location=[37.77,-122.42], zoom_start=12)

In [ ]:
sanfran_map.choropleth(
    geo_data=sanfran_geo,
    data=df_sfcrime,
    columns=['Country', 'Total'],
    key_on='feature.properties.name',
    fill_color='YlOrRd', 
    fill_opacity=0.7, 
    line_opacity=0.2,
    legend_name='Immigration to Canada'
)

# display map
world_map